=== dpabon/SEN2THREE/cfg/L3_GIPP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2015 sp2 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="WATER">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="6"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NO_DATA">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DN_Scale">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedShort">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="4095"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Time">
		<xs:simpleType>
			<xs:restriction base="xs:dateTime">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Min_Time">
		<xs:simpleType>
			<xs:restriction base="xs:dateTime">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Priority">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="MOST_RECENT"/>
				<xs:enumeration value="TEMP_HOMOGENEITY"/>
				<xs:enumeration value="RADIOMETRIC_QUALITY"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SNOW_ICE">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="11"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Algorithm">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ONE_PASS"/>
				<xs:enumeration value="TWO_PASS"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="BARE_SOILS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="VEGETATION">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DS_Scheme_3">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="THIN_CIRRUS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Log_Level">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="NOTSET"/>
				<xs:enumeration value="DEBUG"/>
				<xs:enumeration value="INFO"/>
				<xs:enumeration value="WARNING"/>
				<xs:enumeration value="ERROR"/>
				<xs:enumeration value="CRITICAL"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="UP_Scheme_3">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="URBAN_AREAS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="12"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DS_Scheme_1C">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DS_Scheme_2A">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GIPP_Scheme">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="L3_Synthesis">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Min_Time"/>
				<xs:element ref="Max_Time"/>
				<xs:element ref="Priority"/>
				<xs:element ref="Algorithm"/>
				<xs:element ref="Cirrus_Removal"/>
				<xs:element ref="Shadow_Removal"/>
				<xs:element ref="Snow_Removal"/>
				<xs:element ref="Max_Tiles_Processed"/>				
				<xs:element ref="Max_Cloud_Probability"/>
				<xs:element ref="Max_Invalid_Pixels_Percentage"/>
				<xs:element ref="Max_Aerosol_Optical_Thickness"/>
				<xs:element ref="Max_Solar_Zenith_Angle"/>
				<xs:element ref="Max_Viewing_Angle"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Snow_Removal" type="xs:boolean"/>
	<xs:element name="UP_Scheme_1C">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="UP_Scheme_2A">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CLOUD_SHADOWS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DARK_FEATURES">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tile_Scheme_3">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Cirrus_Removal" type="xs:boolean"/>
	<xs:element name="Classificators">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NO_DATA"/>
				<xs:element ref="SATURATED_DEFECTIVE"/>
				<xs:element ref="DARK_FEATURES"/>
				<xs:element ref="CLOUD_SHADOWS"/>
				<xs:element ref="VEGETATION"/>
				<xs:element ref="BARE_SOILS"/>
				<xs:element ref="WATER"/>
				<xs:element ref="LOW_PROBA_CLOUDS"/>
				<xs:element ref="MEDIUM_PROBA_CLOUDS"/>
				<xs:element ref="HIGH_PROBA_CLOUDS"/>
				<xs:element ref="THIN_CIRRUS"/>
				<xs:element ref="SNOW_ICE"/>
				<xs:element ref="URBAN_AREAS"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Common_Section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Log_Level"/>
				<xs:element ref="DN_Scale"/>
				<xs:element ref="UP_Scheme_1C"/>
				<xs:element ref="UP_Scheme_2A"/>
				<xs:element ref="UP_Scheme_3"/>
				<xs:element ref="Tile_Scheme_1C"/>
				<xs:element ref="Tile_Scheme_2A"/>
				<xs:element ref="Tile_Scheme_3"/>
				<xs:element ref="DS_Scheme_1C"/>
				<xs:element ref="DS_Scheme_2A"/>
				<xs:element ref="DS_Scheme_3"/>
				<xs:element ref="GIPP_Scheme"/>				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Shadow_Removal" type="xs:boolean"/>
	<xs:element name="Tile_Scheme_1C">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tile_Scheme_2A">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LOW_PROBA_CLOUDS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="7"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HIGH_PROBA_CLOUDS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Viewing_Angle">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="40"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MEDIUM_PROBA_CLOUDS">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SATURATED_DEFECTIVE">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Tiles_Processed">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="255"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Cloud_Probability">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Solar_Zenith_Angle">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="70"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Aerosol_Optical_Thickness">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Max_Invalid_Pixels_Percentage">
		<xs:simpleType>
			<xs:restriction base="xs:unsignedByte">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Level-03_Ground_Image_Processing_Parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Common_Section"/>
				<xs:element ref="L3_Synthesis"/>
				<xs:element ref="Classificators"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dpabon/SEN2THREE/cfg/L3_GIPP.xml
<?xml version="1.0"  encoding="UTF-8"?>
<Level-03_Ground_Image_Processing_Parameter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="L3_GIPP.xsd">
  <Common_Section>
    <Log_Level>DEBUG</Log_Level>
    <!-- NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL -->
    <DN_Scale>4000</DN_Scale>
    <UP_Scheme_1C>S2_User_Product_Level-1C_Metadata.xsd</UP_Scheme_1C>
    <UP_Scheme_2A>S2_User_Product_Level-2A_Metadata.xsd</UP_Scheme_2A>
    <UP_Scheme_3>S2_User_Product_Level-3_Metadata.xsd</UP_Scheme_3>
    <Tile_Scheme_1C>S2_PDI_Level-1C_Tile_Metadata.xsd</Tile_Scheme_1C>
    <Tile_Scheme_2A>S2_PDI_Level-2A_Tile_Metadata.xsd</Tile_Scheme_2A>
    <Tile_Scheme_3>S2_PDI_Level-3_Tile_Metadata.xsd</Tile_Scheme_3>
    <DS_Scheme_1C>S2_PDI_Level-1C_Datastrip_Metadata.xsd</DS_Scheme_1C>
    <DS_Scheme_2A>S2_PDI_Level-2A_Datastrip_Metadata.xsd</DS_Scheme_2A>
    <DS_Scheme_3>S2_PDI_Level-3_Datastrip_Metadata.xsd</DS_Scheme_3>
    <GIPP_Scheme>L3_GIPP.xsd</GIPP_Scheme>
  </Common_Section>
  <L3_Synthesis>
    <Min_Time>2014-01-01T00:00:00Z</Min_Time>
    <Max_Time>2014-12-31T23:59:59Z</Max_Time>
    <Priority>RADIOMETRIC_QUALITY</Priority>
    <!-- MOST_RECENT, TEMP_HOMOGENEITY, RADIOMETRIC_QUALITY -->
    <Algorithm>ONE_PASS</Algorithm>
    <!-- ONE_PASS, TWO_PASS -->
    <Cirrus_Removal>true</Cirrus_Removal>
    <Shadow_Removal>true</Shadow_Removal>
    <Snow_Removal>true</Snow_Removal>
    <Max_Tiles_Processed>5</Max_Tiles_Processed>
    <Max_Cloud_Probability>30</Max_Cloud_Probability>
    <Max_Invalid_Pixels_Percentage>2</Max_Invalid_Pixels_Percentage>
    <Max_Aerosol_Optical_Thickness>45</Max_Aerosol_Optical_Thickness>
    <Max_Solar_Zenith_Angle>60</Max_Solar_Zenith_Angle>
    <Max_Viewing_Angle>30</Max_Viewing_Angle>
  </L3_Synthesis>
  <Classificators>
    <NO_DATA>0</NO_DATA>
    <SATURATED_DEFECTIVE>1</SATURATED_DEFECTIVE>
    <DARK_FEATURES>2</DARK_FEATURES>
    <CLOUD_SHADOWS>3</CLOUD_SHADOWS>
    <VEGETATION>4</VEGETATION>
    <BARE_SOILS>5</BARE_SOILS>
    <WATER>6</WATER>
    <LOW_PROBA_CLOUDS>7</LOW_PROBA_CLOUDS>
    <MEDIUM_PROBA_CLOUDS>8</MEDIUM_PROBA_CLOUDS>
    <HIGH_PROBA_CLOUDS>9</HIGH_PROBA_CLOUDS>
    <THIN_CIRRUS>10</THIN_CIRRUS>
    <SNOW_ICE>11</SNOW_ICE>
    <URBAN_AREAS>12</URBAN_AREAS>
  </Classificators>
</Level-03_Ground_Image_Processing_Parameter>
